version: "3.8"
services:

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    #    volumes:
    #      - ./client.json:/consul/config/client.json:ro
    #      - ./certs/:/consul/config/certs/:ro
    networks:
      - consul-local
    command: "agent -server -bootstrap -ui -client=0.0.0.0"
    environment:
      CONSUL_LOCAL_CONFIG: >-
        {
          "node_name": "service-discovery",
          "bind_addr": "0.0.0.0",
          "client_addr": "0.0.0.0",
          "bootstrap_expect": 0,
          "ui": true,
          "addresses" : {
            "http" : "0.0.0.0"
          },
          "ports": {
            "http": 8500
          },
          "acl": {
            "enabled": false,
            "default_policy": "deny",
            "tokens": {
              "initial_management": "root",
              "agent": "root"
            }
          }
        }
    ports:
      - "8500"
      - "8600/tcp"
      - "8600/udp"

  redis-local:
    image: redis:latest
    container_name: redis-local
    networks:
      - local-bridge
    ports:
      - '6379'

  rabbitmq-local:
    networks:
      - local-bridge
    container_name: rabbitmq-local
    image: rabbitmq:3-management
    labels:
      NAME: "rabbitmq-local"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - '5672'
      - '15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    depends_on:
      - mongo
      - jaeger-local
      - redis-local
      - postgres-local

  jaeger-local:
    networks:
      - local-bridge
    container_name: jaeger-local
    image: jaegertracing/all-in-one:1.37
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - '6831/udp'
      - '6832/udp'
      - '5778'
      - '16686'
      - '4317'
      - '4318'
      - '14250'
      - '14268'
      - '14269'
      - '9411'

  mongo-local:
    networks:
      - local-bridge
    container_name: mongo-local
    image: mongo
    restart: always
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 1234

  cassandra-local:
    image: cassandra:latest
    container_name: cassandra-local
    networks:
      - local-bridge
    volumes:
      - /path/to/config:/etc/cassandra
    environment:
      CASSANDRA_SEEDS: cassandra-local
    ports:
      - '9042'

  service-account-rpc:
    container_name: service-account-rpc
    restart: on-failure
    networks:
      - local-bridge
    build:
      context: ./SERVICE-ACCOUNT
    environment:
      CODENAME : ACCOUNT-SERVICE
      RPC_HOST: localhost
      RPC_PORT: 50051
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_HOST: rabbitmq-local
      RABBITMQ_PORT: 5672
      CONSUL_HTTP_ADDR: consul-client:8500
      JAEGER_SERVICE_NAME: ACCOUNT-SERVICE
      JAEGER_AGENT_HOST: jaeger-local
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      JAEGER_REPORTER_LOG_SPANS: true
      REDIS_DB: 1
      REDIS_ADDRESS: redis-local:6379
      REDIS_PASSWORD:
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: 1234
      MONGODB_HOST: mongo-local
      MONGODB_PORT: 27017
      MONGODB_DATABASE: user
      CASSANDRA_HOST: cassandra-local:9042
      CASSANDRA_KEYSPACE: event_driven
    ports:
      - '50051'
    depends_on:
      - redis-local
      - jaeger-local
      - rabbitmq-local
      - consul-client
      - cassandra-local
      - mongo-local

  service-product-rpc:
    container_name: service-product-rpc
    restart: on-failure
    networks:
      - local-bridge
    build:
      context: ./SERVICE-PRODUCT
    ports:
      - '50052'
    depends_on:
      - redis-local
      - jaeger-local
      - rabbitmq-local
      - consul-client
      - cassandra-local
      - mongo-local

  service-cart-rpc:
    container_name: service-cart-rpc
    restart: on-failure
    networks:
      - local-bridge
    build:
      context: ./SERVICE-CART
    ports:
      - '50053'
    depends_on:
      - redis-local
      - jaeger-local
      - rabbitmq-local
      - consul-client
      - cassandra-local
      - mongo-local

  api-gateway:
    restart: on-failure
    container_name: api-gateway
    networks:
      - local-bridge
    build:
      context: ./API-GATEWAY
    ports:
      - '3000:3000'
    depends_on:
      - jaeger-local
      - rabbitmq-local
      - consul-client
      - mongo-local
      - service-account-rpc
      - service-cart-rpc
      - service-product-rpc

networks:
  local-bridge:
    driver: bridge